### ISSUE TITLE
'Payments' list in /dashboard/account shows payments of all users

### ISSUE THREAD

**Issue by bartwr** [urbanlink/dehaagsemunt.nl#8]
There are more payments in the payment list that can be seen on https://dehaagsemunt.nl/dashboard/account . See screenshot below.

![image](https://cloud.githubusercontent.com/assets/899234/20307021/b6d6dec2-ab3d-11e6-8cd5-aeb028932334.png)

I would expect that the list only shows payments made by me.

**Comment by avanderpluijm** [comment]
Thanks, this is fixed now
